# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Authen-SASL-Cyrus
version:      0.13-server
version_from: Cyrus.pm
installdirs:  site
requires:
    Authen::SASL:                  2.08
    Test::More:                    0
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
